services:
  fivem:
    image: spritsail/fivem:latest
    container_name: fivem-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    volumes:
      - ./server-data:/config
    environment:
      - LICENSE_KEY=${FIVEM_LICENSE_KEY}
